from pathlib import Path

import numpy as np

from e57gs.surfels import (
    point_cloud_to_gaussian_surfels,
    quaternion_z_to_normal,
    write_colmap_points_from_ply,
)
from e57gs.gaussian_ply import read_gaussian_ply


def test_quaternion_rotates_z_to_normal() -> None:
    normals = np.asarray([[0, 0, 1], [1, 0, 0], [0, 0, -1]], dtype=np.float32)
    quaternions = quaternion_z_to_normal(normals)
    assert np.allclose(np.linalg.norm(quaternions, axis=1), 1)
    # For q=(w,x,y,z), q * +Z * q^-1 has these components.
    w, x, y, z = quaternions.T
    rotated = np.column_stack((2 * (x * z + w * y), 2 * (y * z - w * x), 1 - 2 * (x * x + y * y)))
    assert np.allclose(rotated, normals, atol=1e-6)


def test_point_cloud_to_gaussian_surfels_preserves_points(tmp_path: Path) -> None:
    dtype = np.dtype(
        [(axis, "<f4") for axis in "xyz"]
        + [(f"n{axis}", "<f4") for axis in "xyz"]
        + [(color, "u1") for color in ("red", "green", "blue")]
    )
    vertices = np.zeros(2, dtype=dtype)
    vertices["x"] = [0.0, 0.01]
    vertices["nz"] = 1.0
    vertices["red"] = [255, 0]
    header = ["ply", "format binary_little_endian 1.0", "element vertex 2"]
    header.extend(
        f"property {'uchar' if vertices[name].dtype.kind == 'u' else 'float'} {name}"
        for name in dtype.names or ()
    )
    header.append("end_header")
    source = tmp_path / "points.ply"
    source.write_bytes(("\n".join(header) + "\n").encode() + vertices.tobytes())

    output = tmp_path / "surfels.ply"
    result = point_cloud_to_gaussian_surfels(source, output)

    parsed = read_gaussian_ply(output)
    assert parsed.vertex_count == 2
    assert parsed.dtype.names is not None
    assert not any(name.startswith("f_rest_") for name in parsed.dtype.names)
    assert result["vertex_count"] == 2

    points_bin = tmp_path / "points3D.bin"
    points_result = write_colmap_points_from_ply(source, points_bin)
    assert points_result["point_count"] == 2
    assert points_bin.stat().st_size == 8 + 2 * 51
    assert int.from_bytes(points_bin.read_bytes()[:8], "little") == 2

    resume = tmp_path / "resume.ply"
    resume_result = point_cloud_to_gaussian_surfels(
        source,
        resume,
        sh_degree=1,
        opensplat_iteration=0,
    )
    resume_parsed = read_gaussian_ply(resume)
    assert resume_result["sh_degree"] == 1
    assert len([name for name in resume_parsed.dtype.names or () if name.startswith("f_rest_")]) == 9
    assert b"comment Generated by opensplat at iteration 0\n" in resume_parsed.header
